Add files via upload
erp12/pyshgp pull request #143
Opened 2020-06-25 00:43 UTC by nayabur

Hi! I created two new demos for the PyshGP examples folder. One is called triple.py, and it's a simple example that walks users through a GP run. The other is called rectangle_area.py, and it demonstrates how to create custom types and instructions.

2020-06-26 05:10 UTC, erp12 requested changes
These examples are great, thanks for putting them together!  I like that we another demonstration of adding custom types and instructions. I have a few minor requests before we merge this pull request.

1. Let's make sure that we run these examples before every public release to check for any changes to pyshgp that may have broke the your code. To help with this, we use a deployment automation tool called [tox](https://tox.readthedocs.io/en/latest/). The only change we need to make is in the `tox.ini` file in the root the project. Just add a couple lines to this section that runs all the example files. You can use the other lines as an template for the syntax.

https://github.com/erp12/pyshgp/blob/6ff3f8e1e3491bea7529687cff2411256db406ad/tox.ini#L37-L47

2. It looks like the start of the commit message is "Add files via upload". That seems like an auto-generated message to me. Git only shows the first line of the commit message in the history, so I think it is helpful to have a 1 sentence summary of what the commit changes. Something like "Adds 2 new examples". Can we change that?

Other than those small changes, this PR is ready to be merged! I think these examples will serve future new users well.

2020-06-26 05:10 UTC, erp12 commented on examples/rectangle_area.py
> +    # returns the Rectangle object's representation
The comments before each method don't tell us much that we don't get from the name of the method. I think the code would be slightly cleaner without them.

2020-06-26 05:10 UTC, erp12 commented on examples/rectangle_area.py
> +)
Very minor and nit-picky suggestion: Although many text editors get this wrong (including the one I use), the python style guides suggest vertical alignment when using`()` for a multi-line statement. For example:

```py
type_library = (
    PushTypeLibrary(register_core=False)
    .register(PushFloat)
    .create_and_register(name="rectangle", underlying_types=(Rectangle,), coercion_func=to_rect)
)
```

2020-06-26 05:10 UTC, erp12 commented on examples/rectangle_area.py
> +        .register(rectangle_from_floats_instruction)
Same whitespace style comment as above.

2020-07-03 18:35 UTC, nayabur commented
I've made all the changes requested. Thank you!

2020-07-07 04:56 UTC, merged

2020-07-07 04:56 UTC, erp12 commented
Looks great, and merged! Thanks for the contribution :)