Fix MemoryError in string operators
erp12/pyshgp pull request #159
Opened 2021-10-13 01:53 UTC by Y1fanHE

Add is_collection=True to PushStrType.

2021-10-13 19:54 UTC, erp12 requested changes
I really appreciate you taking the time to look at the `pyshgp` code and fix this issue! The code change looks good. 

In order to make sure that we don't reintroduce this issue in the future, we should add a test. 

I noticed that somehow the CI stopped running the tests on pull requests... I'll look into that in a future PR.

2021-10-13 19:54 UTC, erp12 commented on pyshgp/push/types.py
> +        # super().__init__("str", (str, np.str_, np.object_))
No need to keep the old buggy code around in comments.

2021-10-13 19:54 UTC, erp12 commented on pyshgp/push/types.py
> +        # Fix MemoryError in string operators
Could you also add a test to `test_stack.py` that attempts to push a large string and checks that it gets truncated properly?

2021-10-14 03:10 UTC, Y1fanHE commented on pyshgp/push/types.py
> +        # Fix MemoryError in string operators
I added the following code in my own branch in `tests/test_stack.py`. The test results seem to be ok.
```
    def test_large_str(self, str_stack: PushStack):
        s = "largestr"*1000
        str_stack.push(s)
        assert len(str_stack.pop()) != len(s)
```
Here is the result.
```
============================================================================================================== test session starts ===============================================================================================================
platform darwin -- Python 3.8.7, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /Users/yifan/Documents/Projects/progsynth/pyshgp
plugins: anyio-3.2.1
collected 128 items                                                                                                                                                                                                                              

tests/test_utils.py ....                                                                                                                                                                                                                   [  3%]
tests/test_validation.py .........                                                                                                                                                                                                         [ 10%]
tests/gp/test_estimator.py ...                                                                                                                                                                                                             [ 12%]
tests/gp/test_evaluation.py ......                                                                                                                                                                                                         [ 17%]
tests/gp/test_genome.py ..............                                                                                                                                                                                                     [ 28%]
tests/gp/test_individual.py ....                                                                                                                                                                                                           [ 31%]
tests/gp/test_population.py .................                                                                                                                                                                                              [ 44%]
tests/gp/test_search.py .                                                                                                                                                                                                                  [ 45%]
tests/gp/test_selection.py .....                                                                                                                                                                                                           [ 49%]
tests/gp/test_translate_validation.py .....                                                                                                                                                                                                [ 53%]
tests/push/test_atoms.py .                                                                                                                                                                                                                 [ 53%]
tests/push/test_core_instructions.py ..                                                                                                                                                                                                    [ 55%]
tests/push/test_instruction_set.py ........                                                                                                                                                                                                [ 61%]
tests/push/test_program.py ......                                                                                                                                                                                                          [ 66%]
tests/push/test_push_validation.py ......                                                                                                                                                                                                  [ 71%]
tests/push/test_stack.py ............                                                                                                                                                                                                      [ 80%]
tests/push/test_state.py .........                                                                                                                                                                                                         [ 87%]
tests/push/test_type_library.py ...........                                                                                                                                                                                                [ 96%]
tests/push/test_types.py .....                                                                                                                                                                                                             [100%]

================================================================================================================ warnings summary ================================================================================================================
pyshgp/push/config.py:11
  /Users/yifan/Documents/Projects/progsynth/pyshgp/pyshgp/push/config.py:11: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Sequence

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================================================= 128 passed, 1 warning in 5.87s =========================================================================================================
```
I wonder how to submit this change? Do I need to open another PR?

2021-10-14 04:06 UTC, erp12 commented on pyshgp/push/types.py
> +        # Fix MemoryError in string operators
Looks great, thanks!

2021-10-14 04:07 UTC, erp12 commented
Looks like this PR is good to go. Thanks again for your contribution!

2021-10-14 04:07 UTC, merged